language: bash
services: docker

env:
  - VERSION=1.3 VARIANT=
  - VERSION=1.2 VARIANT=
  - VERSION=1.2 VARIANT=slim

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="$(awk '$1 == "FROM" { print $2; exit }' onbuild/Dockerfile)${VARIANT:+-$VARIANT}"

script:
  - docker build --pull -t "$image" "${VARIANT:-.}"
  - ~/official-images/test/run.sh "$image"
# the "onbuild" variant has to happen with the base variant because it's FROM it
  - true && [ "$VARIANT" ] || docker build -t "${image}-onbuild" onbuild

after_script:
  - docker images
