language: bash
services: docker

env:
  - DIR=master
  - DIR=1.5
  - DIR=1.5 VARIANT=slim
  - DIR=1.4
  - DIR=1.4 VARIANT=slim
  - DIR=1.3
  - DIR=1.3 VARIANT=slim

install:
  - curl -fsSL https://github.com/docker-library/official-images/archive/master.tar.gz | {
      mkdir -vp ./official-images/;
      tar -C ./official-images/ --strip-components=1 -zxvv official-images-master/test/; }

before_script:
  - eval $(awk '/ELIXIR_VERSION=/ { sub(/@/, "-", $2); print $2; exit }' ${DIR}/${VARIANT}/Dockerfile)
  - image="elixir:${ELIXIR_VERSION#v}${VARIANT:+-$VARIANT}"

script:
  - docker build --pull -t "$image" "${DIR}/${VARIANT}"
  - ./official-images/test/run.sh "$image"

after_script:
  - docker images
